name: Auto-trigger-render

on:
  schedule:
  - cron: "*/20 * * * *"  # every 20mins
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger endpoint
        run: |
          curl https://aztec-real-bot.onrender.com/